package classes;

import javax.swing.*;
import java.awt.*;

public class CreateAccount {

    private String firstName;
    private String lastName;
    private String email;
    private String password;
    private String confirmPassword;
    final String[] type = new String[] {"Job Seeker", "Recruiter"};
    private String organisation;
    private String resumeFile;

    public CreateAccount() {

    }
    /**
     * @param email is String that is a User's email
     * @param password is a String that is a User's password
     * adds the email of the logged-in User to the currentUser ArrayList
     * else false
     */
    public void createJobSeeker(String firstName, String lastName, String email, String password, String confirmPassword) {
        //check if email is new (i.e., not in registered users) - if not, notify that email is not new
        //check if password and confirm password match - if not, return that passwords don't match
        //create new JobSeeker object and add new JobSeeker to database

        User newJobSeeker = new JobSeeker(email, firstName, lastName);

        CSVWriter writer = new CSVWriter();
        String newJobSeekerDetails = String.format("%s,%s,%s", newJobSeeker.getEmail(), newJobSeeker.getFirstName(),newJobSeeker.getLastName());
        writer.newLine(Application.dt_jobSeekers, newJobSeekerDetails);
        //add new email and password to registered users file

        String newRegisteredUserDetails = String.format("%s,%s", newJobSeeker.getEmail(), password);
        writer.newLine(Application.dt_registeredUsers, newRegisteredUserDetails);

    }

    public void createJobSeeker(String firstName, String lastName, String email, String password, String confirmPassword, String resumeFile) {
        //check if email is new (i.e., not in registered users) - if not, notify that email is not new
        //check if password and confirm password match - if not, return that passwords don't match
        //create new JobSeeker object and add new JobSeeker to database
        System.out.println(String.format("The email being passed to the newJobSeeker constructor is: %s", email));
        User newJobSeeker = new JobSeeker(email, firstName, lastName);
        CSVWriter writer = new CSVWriter();
        String newJobSeekerDetails = newJobSeeker.toString();
        writer.newLine(Application.dt_jobSeekers, newJobSeekerDetails);
        //add new email and password to registered users file
        String newRegisteredUserDetails = newJobSeeker.getEmail().concat(",").concat(newJobSeeker.getPassword());
        writer.newLine(Application.dt_registeredUsers, newRegisteredUserDetails);
        //add new resume to resumes file
        writer.newLine(Application.dt_resumes, resumeFile);

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
