package classes;

import javax.swing.*;
import java.awt.*;

/*
 * Recruiter profile is what the job seeker can see of the recruiter.
 */
public class RecruiterProfile {
    private JPanel recruiterProfile;
    private JButton backButton;
    private JScrollPane recruiterProfileDescription;
    private JLabel whoWeAreLabel;
    private JLabel recruiterOrg;
    private JScrollPane jobDescription;
    private JLabel contactLabel;
    private JLabel recruiterEmail;
    private JLabel recruiterWebsite;
    private JLabel recruiterSocial;
    private JLabel recruiterPhoneNo;
    private JLabel jobListingsLabel;
    private JPanel jobListingsPanel;
    private JPanel job1ListingPanel;
    private JLabel job1Title;
    private JLabel job1Score;
    private JLabel job1Company;
    private JPanel job2ListingPanel;
    private JLabel job2Title;
    private JLabel job2Score;
    private JLabel job2Company;
    private JPanel job3ListingPanel;
    private JLabel job3Title;
    private JLabel job3Score;
    private JLabel job3Company;
    private JPanel jobDescriptionPanel;
    private JLabel selectedJobLocation;
    private JLabel selectedJobCompensation;
    private JLabel selectJobCatergory;
    private JButton applyButton;
    private JLabel selectedJobDescription;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

}


