package classes;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class EditCategoryPage {
    private JPanel catPagePanel;
    private JButton addBtn;
    private JButton removeBtn;
    private ClearingTextField catTB;
    private JScrollPane catsScroller;
    private JPanel catsPanel;

    public EditCategoryPage(JFrame frame, CreateJobPage jobPage) {
        Runtime.categories.readFromFile(Config.DT_CATEGORIES);
        GuiHelper.createOptionBox(catsPanel, Runtime.categories.getUserCategories(Runtime.accountManager().getCurrentUser()));
        addBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Runtime.categories.add(catTB.getText(), Runtime.accountManager().getCurrentUser().getEmail());
                Runtime.categories.writeToFile(Config.DT_CATEGORIES);
                GuiHelper.createOptionBox(catsPanel,
                        Runtime.categories.getUserCategories(Runtime.accountManager().getCurrentUser()));
                catTB.setText("");
                frame.setVisible(true);
                frame.repaint();
                jobPage.updateCategories();

            }
        });
        removeBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                for (String catName : GuiHelper.getSelectedOptions(catsPanel)) {
                    Runtime.categories.remove(catName, Runtime.accountManager().getCurrentUser().getEmail());
                }
                Runtime.categories.writeToFile(Config.DT_CATEGORIES);
                GuiHelper.createOptionBox(catsPanel,
                        Runtime.categories.getUserCategories(Runtime.accountManager().getCurrentUser()));
                jobPage.updateCategories();
                frame.setVisible(true);
                frame.repaint();

            }
        });
    }



    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        catPagePanel = new JPanel();
        catPagePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        catsScroller = new JScrollPane();
        catPagePanel.add(catsScroller, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(100, 100), null, 0, false));
        catsPanel = new JPanel();
        catsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        catsScroller.setViewportView(catsPanel);
        catTB = new ClearingTextField();
        catTB.setText("Type in the category to add");
        catPagePanel.add(catTB, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addBtn = new JButton();
        addBtn.setText("Add");
        catPagePanel.add(addBtn, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        removeBtn = new JButton();
        removeBtn.setText("Remove");
        catPagePanel.add(removeBtn, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return catPagePanel;
    }

    public JPanel getCatPagePanel() {
        return catPagePanel;
    }
}
