package classes;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;

public class LoginPage extends JFrame {

    private JPanel mainPanel;
    private final JFrame frame;
    private ClearingTextField emailClearingTextField;
    private ClearingPasswordField passwordClearingPasswordField;
    private JButton loginButton;
    private JButton createNewAccountButton;
    private JTextField textField1;
    private JButton backButton;
    private JButton searchButton;
    private boolean passClicked = false;

    public LoginPage(JFrame frame, AccountManagement accMan) {
        this.frame = frame;

        /**
         * @param email is String that is a User's email
         * @param password is a String that is a User's password
         * @return true if the email and password parameters match a key:value pair in the registeredUsers HashMap
         * else false
         */

        /**
         * if the user clicks the Login button, the method gets the user input for email and password
         * the method invokes the actionUserLogin method of Runtime, which invokes the userLogin method of the Application class
         * email and password are passed as arguments to actionUserLogin and then to userLogin
         * actionUserLogin and userLogin both return true if the user is logged-in, which is used in the method to notify the user
         */
        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (userLogin(accMan)) {
                    JOptionPane.showMessageDialog(null, "You have successfully logged in!");
                } else {
                    JOptionPane.showMessageDialog(null, "The username of password is incorrect.");
                }
            }
        });
        createNewAccountButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Runtime.showCreateAccountPage(frame);
            }
        });
        passwordClearingPasswordField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);

                if (!passClicked) {
                    passwordClearingPasswordField.setText("");
                    passClicked = true;
                }
            }
        });
    }

    public boolean userLogin(AccountManagement accMan) {
        if (validateUser(accMan.getJobseekers())) {
            accMan.setCurrentUser(accMan.getJobseekers().get(emailClearingTextField.getText()));
            return true;
        } else if (validateUser(accMan.getRecruiters())) {
            accMan.setCurrentUser(accMan.getRecruiters().get(emailClearingTextField.getText()));
            return true;
        } else if (validateUser(accMan.getAdmins())) {
            accMan.setCurrentUser(accMan.getAdmins().get(emailClearingTextField.getText()));
            return true;
        } else return false;
    }

    private boolean validateUser(HashMap<String, ? extends User> users) {
        if (users.containsKey(emailClearingTextField.getText())) {
            return users.get(emailClearingTextField.getText()).getPassword().equals(String.valueOf(passwordClearingPasswordField.getPassword()));
        } else return false;
    }

    public JPanel getLoginPagePanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 3, new Insets(20, 20, 20, 20), -1, -1));
        mainPanel.setBackground(new Color(-13224648));
        emailClearingTextField = new ClearingTextField();
        emailClearingTextField.setBackground(new Color(-1973791));
        emailClearingTextField.setText("Email");
        emailClearingTextField.setToolTipText("user@example.com");
        mainPanel.add(emailClearingTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordClearingPasswordField = new ClearingPasswordField();
        passwordClearingPasswordField.setBackground(new Color(-1973791));
        passwordClearingPasswordField.setText("Password");
        mainPanel.add(passwordClearingPasswordField, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textField1 = new JTextField();
        textField1.setBackground(new Color(-11348236));
        mainPanel.add(textField1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 15), new Dimension(-1, 1), 0, false));
        createNewAccountButton = new JButton();
        createNewAccountButton.setText("Create New Account");
        mainPanel.add(createNewAccountButton, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginButton = new JButton();
        loginButton.setText("Login");
        mainPanel.add(loginButton, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        searchButton = new JButton();
        searchButton.setText("Search");
        mainPanel.add(searchButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setText("Back");
        mainPanel.add(backButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}